modularized previous 6 steps, with complete data structure for transc…
NittanyAiAlliance/Admissions-Smart-OCR pull request #175
Opened 2022-02-02 05:40 UTC by AllenGao6

…ript

merged Josh's change for new transcript data structure. Added a few function for the ease of parsing table and column/row assignments

2022-02-03 18:50 UTC, JFamo requested changes

2022-02-03 18:50 UTC, JFamo commented on ocr/table_filter.py
> +        filtered_table.append(check_relevant(table))
Shouldn't append the boolean value - use check_relevant in a conditional and then append the table itself

2022-02-03 18:50 UTC, JFamo commented on ocr/pdf_conversion.py
> +
LINT our spacing

2022-02-03 18:50 UTC, JFamo commented on ocr/pdf_conversion.py
> +        # evaluate_pages(images)
Want to remove these commented lines

2022-02-03 18:50 UTC, JFamo commented on ocr/pdf_conversion.py
> +
More space LINTing

2022-02-03 18:50 UTC, JFamo commented on ocr/data_structures.py
> +    tables = []
I disagree with saving tables here too - opens the door for data inconsistency. Would rather either iterate pages for tables when we need them or maybe implementing a function here that iterates self.pages, iterates that page's tables, and then joins and returns them all. Either way it shouldn't also be stored in this class

2022-02-03 18:50 UTC, JFamo commented on ocr/data_structures.py
> +    def getTableList(self):
See above comment - change this implementation

2022-02-03 18:50 UTC, JFamo commented on ocr/ocr_api.py
> +     # Connect to AWS Textract via boto3
LINT these comments away

2022-02-03 18:50 UTC, JFamo commented on ocr/ocr_api.py
> +def do_textract(bytes_test):
Want to change parameter name from bytes_test to something more relevant

2022-02-03 18:50 UTC, JFamo commented on ocr/ocr_api.py
>  def get_table_csv_results(bytes_test, include_geo=False):
Take this out of the pipeline, we're not using csv anymore, should just call do_textract elsewhere

2022-02-03 18:50 UTC, JFamo commented on ocr/ocr_api.py
>      api.logger.info("From Textract : " + str(response))
Can remove this debug here

2022-02-03 18:50 UTC, JFamo commented on ocr/column_identifier.py
> +def split_row_identifier(table):
Row splitting should probably be located in its own module as a separate component

2022-02-03 18:50 UTC, JFamo commented on ocr/column_identifier.py
> +        # check if there is a need to do row split first
Planning steps would do row splitting after column identification - tag up if we think this should change

2022-02-03 19:07 UTC, JFamo requested changes

2022-02-03 19:07 UTC, JFamo commented on ocr/ocr_api.py
> +    table_reformater(table_list)
Misspelling and might call this something more descriptive - obviously subject to change so not a huge deal

2022-02-04 20:44 UTC, AllenGao6 commented on ocr/column_identifier.py
> +def split_row_identifier(table):
In some cases when duplicate course in a row is detected, I thought it could be easier to split row into two separate tables, then do column identification.

2022-02-04 20:54 UTC, AllenGao6 commented on ocr/column_identifier.py
> +        # check if there is a need to do row split first
Mayme we should tag up for more details

2022-02-04 20:54 UTC, AllenGao6 commented on ocr/data_structures.py
> +    tables = []
agree, changed.

2022-02-04 20:54 UTC, AllenGao6 commented on ocr/ocr_api.py
> +def do_textract(bytes_test):
> Want to change parameter name from bytes_test to something more relevant

Changed to transcript_bytes_stream

2022-02-04 20:54 UTC, AllenGao6 commented on ocr/ocr_api.py
> +    table_reformater(table_list)
left unchanged for now

2022-02-04 20:54 UTC, AllenGao6 commented on ocr/pdf_conversion.py
> +        # evaluate_pages(images)
removed

2022-02-04 20:54 UTC, AllenGao6 commented on ocr/table_filter.py
> +        filtered_table.append(check_relevant(table))
mistakes made unintentionally, good catch!

2022-02-08 20:10 UTC, merged